- docs/HISTORY.txt
- opengever/maintenance/browser/check_reference_prefix_collisions.py
This view checks all repository folders (in all repository roots) for colliding reference number 
(Collision: Two repository folders on the same nesting level having the same reference number prefix)
@deiferni @phgross
> Add view to check for reference number prefix collisions.

- docs/HISTORY.txt
- opengever/maintenance/browser/list_role_principals.py
This view returns all **unique principals that are used in role assignments** (below the adapted context).
Also includes the Plone site (if called on site root) and any principals from global role assignments in `portal_role_manager`.
> Add view to list principals used in role assignments.

- docs/HISTORY.txt
- opengever/maintenance/browser/health_check.py
This adds a `@@health-check` view on the Plone site root that can be used to determine whether an instance is in a healthy state or not.
- This view is public and will be called regularly, so it needs to be cheap! Keep this in mind when changing it.
- Currently it just does a `SELECT 1` on the SQL connection, in order to trigger a potential `MySQL server has gone away`
@phgross
> Add a @@health-check view to be used with httpok and/or HAProxy.

- docs/HISTORY.txt
- opengever/maintenance/browser/health_check.py
`zope.Public` apparently doesn't work.
@phgross @bierik
> Use zope2.Public to protect the @@health-check view.

- docs/HISTORY.txt
- opengever/maintenance/browser/health_check.py
`create_session` was moved from `opengever.ogds.base.utils` to `opengever.base.model` in `opengever.core >= 4.2`. This conditional import makes sure `opengever.maintenance` works with all deployed versions of `opengever.core`.
> Use conditional import in @@health-check view to make it work for og.core < 4.2.

- docs/HISTORY.txt
- opengever/maintenance/browser/list_truncated_rows.py
This view lists all SQL rows that have a value that has the exact same length as the column's max length. These are rows that are likely to have had their values truncated.
Example output:
```
==============================================================================
Checking table: tasks
==============================================================================
COLUMN: Column(u'containing_dossier', VARCHAR(length=512), table=<tasks>)
VALUE: Ein elend langer Dosier Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel Titel …
```
> Add script to list (possibly) truncated rows in SQL.

- docs/HISTORY.txt
- opengever/maintenance/debughelpers.py
- opengever/maintenance/scripts/check_relations.py
Gemäss den Änderungen in https://github.com/4teamwork/opengever.core/pull/982, müssen wir auch im opengever.maintenance die Imports für die Plone 4.3 Kompatibilität anpassen.
@deiferni @lukasgraf
> Adjust imports for Plone 4.3 support.

- docs/HISTORY.txt
- setup.py
There were at least two dependencies missing from `opengever.maintenance`:
- `plone.api` is used by some views. We didn't include this in older versions of `opengever.core`, so since we use it here, we need to declare it.
- The ZCML of `five.grok` needs to be loaded for the template registration with `grokcore.view` to work. So we include the dependency on `five.grok`, then `z3c.autoinclude` will load the ZCML for `five.grok` automatically.
There's a bunch of other dependencies that *should* be specified, but they're not critical at the moment - in reality, we **always** use `opengever.maintenance` with `opengever.core`, so those dependencies are there. 
> Declare missing dependencies

- .gitignore
- base-testing.cfg
- opengever/maintenance/testing.py
- opengever/maintenance/tests/test_grokking.py
- setup.py
- test-og-2.7.x.cfg
- test-og-2.8.x.cfg
- test-og-2.9.x.cfg
- test-og-3.0.x.cfg
- test-og-3.1.x.cfg
- test-og-3.2.x.cfg
- test-og-3.3.x.cfg
- test-og-develop.cfg
This adds a basic testing setup to test against the currently supported versions of `opengever.core`:
- `2.7`
- `2.8`
- `2.9`
- `3.0`
- `3.1`
- `3.2`
- `3.3`
- `develop`
Also includes a simple testing layer based on the `COMPONENT_REGISTRY_ISOLATION` layer that loads the ZCML for `opengever.maintenance` to trigger any import errors that would prevent the instance from booting.
Many of these tests will currently **fail** because we haven't yet addressed the problems they're supposed to uncover.
> Add testing setup to test against supported versions of opengever.core

- opengever/maintenance/compat.py
- opengever/maintenance/pdf_conversion/helpers.py
- opengever/maintenance/scripts/convert_pdfs.py
- test_all.sh
This PR introduces a `compat` module that should be used for all conditional imports, compatibility hacks etc... to ensure the `opengever.maintenance` package is compatible with all supported versions of `opengever.core`.
"Compatible" in this context means that it doesn't produce errors (like `ImportErrors` or other ZCML/Grok related errors) **on startup** that would result in the instance not booting. Whether or not it's worth to make the actual *functionality* compatible with all versions will have to be determined on a case-by-case basis.
@deiferni @phgross
> Restore compatibility with all supported og.core versions

- base-testing.cfg
Because the newest version (1.12) of collective.recipe.template, in particular this PR, breaks compatibility for zc.buildout 1.4.
> Pin down `collective.recipe.template` for tests.

- docs/HISTORY.txt
- opengever/maintenance/debughelpers.py
Add a fake `-c` option to work around an issue with recent versions of `plone.recipe.zope2instance`'s `bin/interpreter` script.
The `bin/interpreter` script fails at argument parsing and passes a `-c` to the argument parser of `bin/instance run` scripts.
See https://dev.plone.org/ticket/13414 for details.
@deiferni @phgross
> Fix bin/instance run for recent plone.recipe.zope2instance versions

- docs/HISTORY.txt
- opengever/maintenance/scripts/update_zope_user_pw.py
Only handles users in the `ZODBUserManager` on the Zope Application Root.
> Add script to update the PW for a user in the ZODBUserManager.

- docs/HISTORY.txt
- opengever/maintenance/scripts/obj_stats.py
- opengever/maintenance/stats/catalog.py
- opengever/maintenance/stats/zodb.py
Includes the necessary functions and a script that collects object stats from catalog and ZODB returns them as JSON.
Example output:
```json
{
"fd": {
"mails": 5,
"repositoryfolders": 76,
"documents": 34,
"contacts": 3,
"forwardings": 1,
"zodb_objects": 12577,
"tasks": 2,
"tasktemplates": 1,
"dossiers": 13,
"repositoryroots": 1,
"base_documents": 39
}
}
```
> Add script for catalog and ZODB object stats

- docs/HISTORY.txt
- opengever/maintenance/scripts/set_shared_secret.py
Kann nützlich sein um bei einem Mandantenverbund für alle ein `shared_secret` hinterlegen will. 
Funktioniert gleich wie die [`manage_setSharedSecret`](https://github.com/plone/plone.session/blob/master/plone/session/plugins/session.py#L305) Methode, welche vom ZMI angesteuert wird.
@lukasgraf @deiferni
> Add a script that set a shared secret in the acl_users session management.

- docs/HISTORY.txt
- opengever/maintenance/scripts/find_long_task_titles.py
This script will identify Plone tasks whose title is longer than 255 characters and output a list of them in CSV format.
@deiferni
> Add script to find tasks with title > 255 chars.

- docs/HISTORY.txt
- opengever/maintenance/scripts/crop_long_titles.py
This script crops titles that exceed the respective SQL limit for dossiers and tasks.
- If the object has a description field and it's empty, the old title will be saved there.
- A journal entry will be generated on the object itself or the next parent that has a journal.
- There is a dry-run mode (`-n`)
> Add script to crop long dossier and task titles.

- opengever/maintenance/scripts/fix_incorrectly_synched_tasks.py
Mithilfe dieses Scripts können Aufgaben welche nicht korrekt ins OGDS synchronisiert wurde aufgespürt und mit der Option `-r` auch gleich korrigiert werden.
Der Output des Scripts sieht folgendermassen aus:
```
bin/instance run scripts/fix_incorrectly_synched_tasks.py -s rk -r
------------------------------------------------------------------------------
------------------------------------------------------------------------------
3 incorrectly_synched tasks detected.
------------------------------------------------------------------------------
[(<Forwarding at /rk/eingangskorb/forwarding-1>, 'not existing'),
(<Forwarding at /rk/eingangskorb/2015/forwarding-3>,
"['physical_path', 'issuer']"),
(<Forwarding at /rk/eingangskorb/2015/forwarding-4>, "['sequence_number']")] …
```
> Added script to detect and fix/reindex incorrectly synched tasks.

- docs/HISTORY.txt
- opengever/maintenance/scripts/check_for_rid_key_errors.py
This script attempts to discover inconsistencies between the Plone Lexicon and ZCTextIndexes.
It should detect cases where a ZCTextIndex references a word (by an integer word ID (`wid`)) that doesn't exist in the lexicon (any more). It does this by trying to fetch all indexed data, for all indexes, for all brains.
In the case of ZCTextIndexes, this will cause `getEntryForObject` to look up a list of word IDs in the lexicon, and trigger a KeyError if that word isn't in the lexicon.
It seems that the only reliable way to fix this situation is to first **CLEAR** all the affected indexes, and then rebuild them.
An logfile of the first analysis done with this script is at `0000oglx13:~/debug_logs/rid_key_errors_analysis_2015-09-15.log`
The fix for the corresponding upgrade-step is in …
> Add script to discover inconsistencies between the Plone Lexicon and ZCTextIndexes

- docs/HISTORY.txt
- opengever/maintenance/scripts/fix_broken_indices.py
Add script to fix inconsistencies between index and lexicon for bug fixed in  https://github.com/4teamwork/opengever.core/pull/1224.
The broken indices have been found with another script added in https://github.com/4teamwork/opengever.maintenance/pull/34. Only `document_author` and `searchable_filing_no` seem to be affected.
> Add script to fix indices affected with inconsistencies.

- docs/HISTORY.txt
- opengever/maintenance/scripts/find_uncatalogued_mails.py
- opengever/maintenance/scripts/fix_mail_class_intids.py
- opengever/maintenance/scripts/fix_mail_class_query.py
When migrating the class of contenttypes one must ensure that all the references to instances are updated/changed as well, see https://www.fourdigits.nl/blog/changing-your-packagename#1411464714874959. This PR adds two scripts to recover from incorrectly migrated mail classes and make sure that all references are up to date as well.
- fix_mail_class_intids: fixes references from the `intid` utility and should theoretically migrate all broken mails
- fix_mail_class_query: due to historical reasons, it was used first to recover from a failed migration but did not update the underlying problem, i.e. references from the intid utility. It should be run after above script to make sure that all is well.
See https://github.com/4teamwork/opengever.core/issues/1215.
> Add scripts to fix mail migrations.

- opengever/maintenance/scripts/fix_broken_sortable_title_indexes.py
- test-og-2.7.x.cfg
- test-og-2.8.x.cfg
- test-og-2.9.x.cfg
- test-og-3.1.x.cfg
Find brains which has wrongly not been reindexed by the [plone.app.upgrade.v43.reindex_sortable_title](https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v43/alphas.py#L11) and reindex them.
Additionally I've dropped the support for GEVER versions < 3.0
@lukasgraf @deiferni 
Extranet: https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20255
> Added Script to fix broken sortable title indexes

- opengever/maintenance/browser/refnum_selfcheck.py
Template dosssiers use their title as local part of the reference number. We don't want to validate those.
> Don't check refnums for template dossiers, they are different.

- opengever/maintenance/scripts/use_canonical_document_ids.py
- opengever/maintenance/utils.py
Dieser PR beinhaltet ein Skript `use_canonical_document_ids.py` welches Dokumente mit falscher ID zur kanonischen Form `document-[id]` konvertiert.
Zum Testen können Dokument-ids z.B. folgendermassen geändert werden:
```python
def break_document_ids(options):
"""DEV-method, use to break the document ids.
"""
catalog = api.portal.get_tool('portal_catalog')
brains = catalog.unrestrictedSearchResults(
portal_type='opengever.document.document')
for number, brain in enumerate(brains):
old_name = brain.id
new_name = "with spaces {}".format(number)
obj = brain.getObject()
api.content.rename(obj=obj, new_id=new_name)
print "broke {} to {} ({})".format(old_name, new_name,
'/'.join(obj.getPhysicalPath()))
if not options.dry_run:
transaction.commit()
print "done breaking."
```
> Add script to make document ids canonical.

- docs/HISTORY.txt
- opengever/maintenance/scripts/catalog_stats_by_month.py
- opengever/maintenance/stats/catalog.py
Dumps JSON output with catalog stats (GEVER specific content types) grouped by month. 
Example usage: 
```
bin/instance run catalog_stats_by_month.py 2015-01 2016-03
```
/cc @deiferni *(as discussed, no review needed)*
> Add script to dump catalog stats grouped by month.

- opengever/maintenance/browser/refnum_selfcheck.py
- opengever/maintenance/scripts/reset_dossier_refnums.py
Closes #48 
Das Script `reset_dossier_refnums.py` vergibt allen Dossiers (`IDossierMarker`) neue Referenznummern und indexiert alles neu.
Das Script wird mit `./bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/reset_dossier_refnums.py`
**Implementation:**
- Das Script setzt den Dossier-Referenznummern storage auf jedem parent eines dossier (d.h. repository folders und dossiers) neu, indem ein neues `PersistentDict` zugewiesen wird.
- Anschliessend wird regulär per adapter dem Dossier die nächste freie Nummer vergeben.
- Der Katalog wird für alle Objekte aktualisiert (Metadaten + `reference`-Index).
**Integrität, Schutzmechanismen und Logging:**
- Es wird mit `transaction.doom` gestartet; die entsprechende Condition muss im Code geändert werden wenns ernst gilt …
> Script zum Zurücksetzen der Dossier-Referenznummern

- test-og-3.7.x.cfg
A new minor release requires tests for its version.
> Add tests for opengever release 3.7.x.

- opengever/maintenance/scripts/fix_retention_period.py
Skript zum nachträglichen setzen der Aufbewahrungsdauer von Ordnungspositionen und Dossiers, falls diese nicht korrekt aus dem initialen Excel eingelesen wurden.
**Ausführen:**
Das Skript wird mit `bin/instance run` ausgeführt. Es stehen folgende Paramter zur Verfügung:
- `-p [profile_name]`, z.B. `-p 'opengever.examplecontent:repository_minimal'`, generic setup profil, welches das Excel file beinhaltet
- `-v` verbose mode
- `-n` dry-run
**Implementation:**
Die Ordnungspositionen werden nur korrigiert, falls sie noch identisch zum Excel sind. Das bedeutete, dass sowohl die Referenznummer wie auch der Titel mit dem Excel übereinstimmen müssen. Zudem muss die Aufbewahrungsdauer den Defaultwert von `5` haben (_dies stimmt bei den betroffenen Kunden gerade so, könnte theoretisch aber auch …
> Fix-Skript für nicht eingelesene retention_period.

- docs/HISTORY.txt
- opengever/maintenance/browser/health_check.py
This will make the `@@health-check` view also available on the **Zope Application Root**
(*by registering it for `Interface` - `grok.context()` can't be used multiple times for the same view or take more than one interface* 😦 )
This will allow us to configure our `HttpOk` plugins to point to a health check view that
- is on the **Zope Instance** (`HttpOk` are per-instance, not per-site)
- is accessible for **Anonymous** users (otherwise the `HttpOk` plugin will always just see the login form)
- uses the **`SQLAlchemy` connection** (in order to detect `MySQL server has gone away` or similar issues)
@phgross
> Make @@health-check view also available on Zope App Root.

- docs/HISTORY.txt
- opengever/maintenance/scripts/bumblebee_installation.py
The `scripts` directory from `opengever.core` is not part of the egg, therefore it makes more sense to add the bumblebee installation script to the opengever.maintenance package.
@deiferni
> Move bumblebee installation script from og.core to og.maintenace.

- opengever/maintenance/scripts/move_documents_in_proposal_to_dossier.py
This was only allowed very briefly during development. There is no
upgrade step. Some cases seem to have sneaked into our staging environment,
so we fix these by moving the affected documents to the proposals dossier.
Closes https://github.com/4teamwork/opengever.core/issues/2084.
> Add script to move documents in proposals.

- docs/HISTORY.txt
- opengever/maintenance/browser/pdb_breakpoint.py
Sometimes its easier to call the `pdb-breakpoint` view directly on a specific content.
@deiferni
> Make pdb breakpoint view, accessible on every context.

- opengever/maintenance/browser/repository_report.py
This view will build a repository report that contains a listing of all repository folders in CSV format.
The report includes the **reference number**, **repository folder title** and **responsible org unit** (if enabled).
Example output:
```
Ordnungspositionsnummer;Ordnungsposition;Federführendes Amt
0;ALLGEMEINE VERWALTUNG;
00;Allgemeines;
000;Kantonsaufbau;
000.0;Gesetzessammlung LLL;
001;Kantonsgebiet;
001.0;Grundlagen;
001.1;Grenzbereinigungen;
001.2;Nomenklaturkommissionen;
01;Legislative und Exekutive;AFJ
...
```
The implementation contains a hardcoded sorter for the grouped_by_three reference number formatter that can be removed as soon as 4teamwork/opengever.core#2459 is deployed everywhere.
@deiferni
> Add view to produce a repository report.

- test-og-3.11.x.cfg
This PR adds a test configuration file to test `opengever.maintenance` against the recently created release 3.11.0.
> Add tests for new release 3.11.0.

- test-og-3.11.x.cfg
Use 3.11.1 release in 3.11.x release compatibility tests.
> Bump 3.11.x tests configuration to latest release; 3.11.1.

- opengever/maintenance/scripts/mysql2postgres.py
Usage:
```
bin/instance run mysql2postgres.py --old-dsn mysql://olduser:oldpw@host/olddb
```
Tested for: KGS Version 3.4.8
- Create Backups as necessary
- Shut down your MySQL-based GEVER deployment
- Make sure PostgreSQL is running, and create the new PG DB using `createdb`
- Include `psycopg2` in your `${buildout:instance-eggs}`
- Change the OGDS connection string (`<db:engine url="..." />`) from MySQL to
the new PostgreSQL DB to be migrated into
- Run `bin/buildout`
- Start ZEO using `bin/zeo start`
- Run this migration script:
`bin/instance0 run mysql2postgres.py --old-dsn $OLD_MYSQL_DSN`
- Remove `opengever.mysqlconfig` / `MySQL-python` from buildout
- Run `bin/buildout`
- Start the deployment up again
Tested against KGS Version 3.4.8:
- Set up two fresh deployments with example …
> Add script to migrate GEVER DB from MySQL to PostgreSQL

- opengever/maintenance/scripts/mysql2postgres.py
mysql2postgres: Don't attempt to cast unicode to str for TEXT columns.
@deiferni
> mysql2postgres: Don't attempt to cast unicode to str for TEXT columns.

- test-og-2017.1.x.cfg
- test-og-3.0.x.cfg
- test-og-3.2.x.cfg
- test-og-3.3.x.cfg
- add tests for 2017.1.0 release
- drop tests for now unused versions
> update og-maintenance test configuration

- opengever/maintenance/scripts/bumblebee_installation.py
Use intermediate commit of `ftw.bumblebee` during reindex, if available. See https://github.com/4teamwork/ftw.bumblebee/pull/111 for more information.
_This will also work if intermediate_commit is not specified on the command line._
> Use intermediate commits during reindex if available.

- opengever/maintenance/scripts/bumblebee_installation.py
Bumblebee installation script: Skip documents with more than 50 versions when calculating checksums for versions, and log them.
> Bumblebee installation script: Skip documents with more than 50 versions

- setup.py
Ref. [PEP-440](https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number).
> Canonicalize the dev version in order to squelch a setuptools warning

- docs/HISTORY.txt
- opengever/maintenance/scripts/mysql2postgres.py
This updates the `mysql2postgres.py` script for the current GEVER version.
Updated sequence definitions from current `master` and tested one MySQL -> PostgreSQL migration using the script.
If any of the sequences found in the DBs were to be unmapped, the script would complain, so it's safe in case it isn't 100% up-to-date.
> Update MySQL2PostgreSQL script: Add new sequence definitions.

- test-og-develop.cfg
Instead of deprecated develop kgs instead versions from https://raw.githubusercontent.com/4teamwork/opengever.core/master/versions.cfg. The develop kgs is deprecated and no longer maintained, thus versions mismatched.
This fixes the currently broken tests against master since now the versions pinnings are correct.
> Extend from opengever.core master versions.

- docs/HISTORY.txt
- opengever/maintenance/scripts/fix_journal_message_mappings.py
Fixes encoding for zope.i18nmessageid.Message mapping values, for journal entries of objects which has been created with an OGGBundle import.
See https://github.com/4teamwork/opengever.core/pull/3369 for more details.
> Add script to fix broken journal entries after OGGBundle import.

- opengever/maintenance/scripts/unify_responsible_org_units.py
This script makes sure that the `responsible_org_unit` on Inbox and Repository Folder types is consistent in casing (lower/upper case) with whatever is stored in OGDS as the org unit `unit_id`.
> Add script to unify casing of responsible org units for inboxes and repository folders

- opengever/maintenance/scripts/check_datetime_indexes_for_falsy_values.py
A bin/instance run script which reports catalog datetime indexes which contain falsy values.
A datetime index must not contain falsy values, otherwise the affected brains will be removed from a result set when ordered by this index.
Background:
Sorting by a DateTime index containing falsy values is problematic: the index has not enough infos to decide whether the falsy entries should be ordered on top or on bottom of the list. The index simply removes the falsy values.
ftw.table's catalog source contains a workaround which prevents the catalog from sorting by date indexes in general and does this by hand afterwards. This is a bad solution.
The correct solution is to extend the indexers of date indexes so that they always return a datetime. The indexer must decide whether this is a …
> Script for checking datetime indexes for falsy values.

- opengever/maintenance/scripts/list_userids_differing_in_case.py
Add script that checks for users that are present in OGDS and LDAP with IDs that differ ONLY by case and lists them in a mapping.
(This is used to produce the mapping used for the AI usermigration).
> Add script that checks for users that are present in OGDS and LDAP with IDs that differ ONLY by case

- opengever/maintenance/configure.zcml
- test-og-2017.4.x.cfg
- test-og-2017.5.x.cfg
- test-og-2017.6.x.cfg
- Add tests for the recent 2017.x releases.
- Add a workaround for an issue with missing directive definitions solved in https://github.com/4teamwork/opengever.core/pull/3590
_There is a wiki page that documents how to release, please try to remember
that it exists :wink:
https://github.com/4teamwork/opengever.core/wiki/Neuer-GEVER-Release_
> Add test for recent releases.

- test-og-2017.1.x.cfg
- test-og-2017.3.x.cfg
- test-og-3.5.x.cfg
- test-og-3.6.x.cfg
- test-og-3.8.x.cfg
- test-og-3.9.x.cfg
According to `matrix` the following versions of opengever.core/kgs respectively are still installed somewhere:
3.4.1 (og.core: 4.5.1)
3.4.8 (og.core: 4.5.8)
3.7.1 (og.core: 4.8.1)
3.10.3 (og.core: 4.14.1)
3.11.1 (og.core: 4.15.1)
3.11.6 (og.core: 4.15.6)
3.11.7 (og.core: 4.15.7)
2017.2.3
2017.2.4
2017.2.5
2017.4.0
2017.5.0
2017.5.1
2017.6.0
2017.6.1
With this PR i propose to no longer test against the not installed releases as i don't see why we would install them.
> Drop no longer installed releases from being tested.

- test-og-2017.6.x.cfg
> Test against most recent 2017.6.x release.

- docs/HISTORY.txt
- opengever/maintenance/scripts/fix_one_note_mimetypes.py
With https://github.com/4teamwork/opengever.core/pull/3660 the mimetype for onenote document has been fixed. But the fix in #3660 solves the problem only for new but not for existing documents. Because we don't have an index for the contentType or the filename an upgradestep would be way to longrunning comparing how many documents are effected. Therefore we add this simple opengever.maintenance script. We can run offside the release.
> Add fix_one_note_mimetype script.

- docs/HISTORY.txt
- opengever/maintenance/scripts/persist_default_value_for_paperform.py
* Fires both the Python GC and the site GC every 100 `brain.getObject()`
* Persists unpersisted default values for `preserved_as_paper` to the current registry default
> Add a script to persist stored as paper form default values

- opengever/maintenance/scripts/blobify_namedfiles.py
Add a script to remove named files and convert them to named blob files. Occasionally we seem to have some `NamedFile` instances left. Those should be a `NamedBlobFile`, so this script will perform the conversion.
Successfully tested on a customers release-test deployment with >100 broken mails.
> Blobify namedfiles, i.e. convert NamedFile to NamedBlobFile

- opengever/maintenance/scripts/set_iworks_mimetypes.py
- test-og-3.4.x.cfg
Maintenance script to set the mimetypes for IWorks documents.
This complements https://github.com/4teamwork/opengever.core/pull/3835 where the new mimetypes were introduced.
> Script to set mimetypes for IWorks documents (numbers, pages, keynote).

- opengever/maintenance/scripts/rebuild_uid_index.py
Some of our deployments have a broken UID index. 
This PR adds a script to rebuild the UID index, als also provided by https://github.com/4teamwork/ftw.copymovepatches/blob/65df9a04503161ed5df54bd255e0724d25ce4293/ftw/copymovepatches/browser/catalog_fixes.py#L20. 
It also logs to stdout while reindexing.
> Add script to rebuild the UID index.

- docs/HISTORY.txt
- opengever/maintenance/scripts/fix_mail_message_caches.py
Add script to fix mail message caches. This is needed for fixing mails where the (peristent) `mail._message` cache hasn't been initialized properly.
Creates `mail._message` for objects that don't have it, reindexes the object if necessary. Can be run with `-n` (dry run) to just perform an analysis of affected objects.
> Add script to fix mail message caches.

- opengever/maintenance/scripts/unindex_duplicates_by_path.py
We have observed that due to a currently unknown bug certain objects are registered twice in the catalog. This script can be passed a path and then tries to figure out if that object is broken and if so, tries to remove the duplication.
Tries to be extra careful and verbose. Only handles the observed case of exactly one duplicate.
>  Add script to unindex duplicates from the catalog

- opengever/maintenance/scripts/fix_dossier_resolvability.py
Provides functionality to fix the resolvability of a dossier with already resolved subdossiers that are now in an 'invalid' state. Invalid means that some of the documents in a dossier have a document date outside its dossiers start-end range. This most likely happens when we generate a journal pdf while closing a dossier with an already defined end-date.
> Add script to fix dossier resolvability.

- opengever/maintenance/scripts/fix_dossier_resolvability.py
- also reindex the object
- don't limit the query to documents, also include mails
- move print only print documents that are actually fixed
> Amend the dossier availability fix script

- opengever/maintenance/scripts/statistics_favorites.py
In order to find out how many users are actually using favorites, this script dumps simple favorites usage statistics. With the -d parameter the statistics can be dumped to a directory as a json file.
The script prints something like:
```python
{
"favorites_enabled": true,
"stats": [
{
"max": 5,
"median": 3.5,
"min": 2,
"root_id": "ordnungssystem",
"total_users": 7,
"with_favorites": 2
}
]
}
```
and dumps into files like `http-localhost-8080-fd.json` (based on public URL).
The idea is that I can run this script for e.g. all SaaS deployments and dump the results to one directory.
> Add favorites statistics script.

- opengever/maintenance/scripts/fix_permissions_on_docs_moved_out_of_private_area.py
This script updates object permissions for documents (and mails) that **have been moved out of a user's private area** before the fix from 4teamwork/opengever.core#4092 was in place.
It recognizes documents that have incorrect permissions by the fact that they still have `MemberAreaAdministrator` in their `allowedRolesAndUsers` index but are in the outside of a private area (in the public repository).
> Add script to fix permissions on docs moved out of private area

- opengever/maintenance/scripts/delete_orphaned_ogds_tasks.py
This script **DELETES** orphaned OGDS tasks.
OGDS tasks are considered orphaned if no Plone task exists at the `physical_path` that the OGDS record points to.
These can occur as a leftover if the zope instance was killed during task creation for some reason.
Usage:
```
bin/instance run delete_orphaned_ogds_tasks.py --i-know-what-im-doing -n
```
The script has several safeguards. Before finally considering a task orphaned, it checks that
- we can traverse to the physical path of the container that the task supposedly is in
- the physical path doesn't appear in the Plone catalog
- the IntID doesn't resolve to a Plone object
- the task is neither a subtask nor does it have a predecessor
> Add script to delete orphaned OGDS tasks.

- opengever/maintenance/scripts/calculate_missing_bumblebee_checksums.py
Calculates Bumblebee checksums for documents that are missing them, and also stores those checksums in Bumblebee.
This may be needed for documents created via the REST API before 4teamwork/opengever.core#4139 was deployed.
> Add script to calculate missing Bumblebee checksums.

- opengever/maintenance/scripts/count_checked_out_docs.py
Add script to count checked out docs per user.
Example output:
```
{'avg': 10.5,
'max': 20,
'med': 10.5,
'min': 1,
'counts': {
'lukas.graf': 20,
'philippe.gross': 1
}
}
```
> Add script to count checked out docs per user

- opengever/maintenance/scripts/reindex_subject_index_on_solr.py
For large GEVER deployments we disable the potentially longrunning Upgradestep `ReindexSubjectIndexOnSolr`, this script allows to triggers the reindex separately. 
See https://github.com/4teamwork/opengever.core/pull/4289 for more information.
> Add script to reindex subject index on solr.

- test-og-2018.3.x.cfg
Bump `2018.3.x` tests to `2018.3.2`.
> Bump 2018.3.x tests to 2018.3.2

- opengever/maintenance/scripts/bumblebee_store_since.py
Add script to store documents since a given date in Bumblebee.
It does so by patching the `GeverBumblebeeConverter`'s `batch_query` to include a date range limitation.
> Add script to store documents since a given date in Bumblebee.

- opengever/maintenance/scripts/delete_journal_entries.py
Script can be used with `bin/instance run`:
```
bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/delete_journal_entries.py -u 'a7b786f88c7a4680b8a51a366dca8e1d'
```
Background / Use Case: https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/234.
> Add maintenance script to remove journal entries of an object

- opengever/maintenance/scripts/reimport_document_dates.py
In SG wurde nach der Migration eines Mandanten festgestellt, dass falsche Werte für das Metadatum  `document_date` geliefert wurden. Diese Script korrigiert dieses Dokumentdaten nun anhand eines neuen Bundles, dabei wird nur documents.json verwendet. 
Dabei gilt: Es werden nur Dokumentdaten korrigiert welche älter sind als das Migrationsdatum.
Siehe auch
https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/298
ℹ️ Please wait with a merge, I'll do a testrun on the migration server first.
> Add Script to reimport document_dates from a bundles documents.json.

- opengever/maintenance/scripts/fix_non_persisted_values.py
This script **persists field values on all objects**. It does so by querying the catalog for all objects, and persisting any field values that currently aren't persisted (=volatile) by
- iterating over all of the schemas of the object's portal_type
- iterating over every field of each schema
- determining the value that the field should have
Determining the correct value is done using a few different strategies:
- Fields which are **optional** and **don't have any default** are whitelisted as such. These fields get their **missing_value** persisted.
- Fields which are **optional** and have a **static default** (i.e. no `defaultFactory`) are whitelisted as such. These fields get their **static default** persisted.
- For more complex cases, some **custom handlers** are used to deal with …
> Add script to fix non-persisted values.

- opengever/maintenance/browser/warmup.py
- opengever/maintenance/configure.zcml
- opengever/maintenance/monitor/configure.zcml
- opengever/maintenance/monitor/health.py
- setup.py
Implement monitor server for HAProxy health checks.
This allows us to run a single threaded ZServer per instance and do the HAProxy health checks with the monitor server using a different port.
The monitor server port needs to be configured in zope.conf. E.g.
```
zope-conf-additional +=
<product-config five.z2monitor>
bind 127.0.0.1:10181
</product-config>
```
If not configured, the monitor server is not started.
> Monitor server

- docs/HISTORY.txt
- opengever/maintenance/scripts/activate_solr.py
- opengever/maintenance/scripts/solr_maintenance.py
- Add solr-maintenance bin/instance run script, which allows to start solr-maintenance jobs from the shell. `reindex`, `clear`, `diff` and `sync` are the supported modes.
- Use sync mode in the solr activate script for indexing content.  So its also possible to reindex and prepare a large GEVER deployment for the solr activation and run the solr activation in a separate step.
> Improve solr activation and add a solr maintenance script

- opengever/maintenance/scripts/fix_solr_filesize_and_changed.py
The `changed` index was also missing in the solr conf. See https://github.com/4teamwork/opengever.core/pull/5166 for more information.
> Extend the solr fix script with reindexing the `changed` index.

- docs/HISTORY.txt
- opengever/maintenance/scripts/validate_object_schema_conformance.py
We add a script which checks all objects for conformance to their schemata. The script outputs statistics to a STDERR/STDOUT as well as to a log file and writes a detailed CSV report.
We output 3 different types of statistics:
**Global statistics** showing a summary of the number of objects of each types and how many are conforming or not to their schemata.
**Detailed statistics** For each `portal_type` we present two tables. 
* In the first one we list the problematic fields and generally what type of problem was present (missing value, invalid, or somehow validation failed).
* In the second table we list the different types of errors encountered for each field.
With the `--verbose` option, we aggregate the errors not according to error type but error message. This is useful as it shows …
> Add script to check object conformance to schema.

- docs/HISTORY.txt
- opengever/maintenance/monitor/configure.zcml
As this is a new package, it would require a buildout of gever in order to use newer versions of opengever.maintenance.
> Make import of five.z2monitor conditional.

- opengever/maintenance/scripts/add_missing_file_extensions.py
Filenames of the client include dots, so that os.splitext does not work. Instead we use the GeverFileNameNormalizer.split_filename_extension which uses a regex to determine the extension.
> Fix add_missing_file_extensions script.

- test-og-2017.2.x.cfg
- test-og-2017.4.x.cfg
- test-og-2017.5.x.cfg
- test-og-2019.1.x.cfg
- test-og-3.10.x.cfg
- test-og-3.11.x.cfg
- test-og-3.7.x.cfg
- Add a new test configuration to automatically test the latest 2019.1.x release.
- Drop tests for versions no longer used in production. `opengever.zug` is the oldest deployment, they are currently running on `2017.6.8`.
> Add tests for new release 2019.1.0, drop old tests.

- opengever/maintenance/scripts/list_dossiers_shared_with_group.py
More specifically the scripts finds all dossiers on which the group is directly assigned local roles through sharing. This is for https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/605
> Add script to list all dossiers shared with a group.

- docs/HISTORY.txt
- opengever/maintenance/scripts/export_dossier_structure_as_excel.py
The script takes a path as argument and generates an excel file of all the dossiers in that context. I did not bother using the translation machinery for column titles, instead simply set them manually in German. Chances are, this would otherwise come out english and that is probably not what is expected here.
resolves https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/599
> Add script to export the dossier structure of a repofolder to an excel file.

- base-testing.cfg
Catch up with changes to test-base configuration introduced in https://github.com/4teamwork/ftw-buildouts/pull/150.
We can now drop separate/additional configuration of the `[test]` section as the arguments provided in https://github.com/4teamwork/ftw-buildouts/pull/150 can be used.
> Stop executing opengever.core tests in test runner.

- opengever/maintenance/scripts/fix_non_persisted_values.py
This changes the `fix_non_persisted_values` script to also report how many values actually got **changed** (not just persisted).
Since this should only happen for very specific fields, this is an important plausibility check to make sure we don't accidentally persist incorrect values.
> fix_non_persisted_values script: Report value changed counts by field.

- opengever/maintenance/scripts/fix_non_persisted_values.py
Update the script to fix non persisted values for new field `ITask.revoke_permissions` and indexers `opengever.base.indexes.has_sametype_children` and `opengever.base.indexes.changed`.
Also fix an issue with printing output to the console.
> Update the script to fix non persisted values for new fields and indexers.

- opengever/maintenance/scripts/fix_non_persisted_values.py
Report if the value has changed in any field, not just the last field from the scope of the previous list comprehension.
> Fix value changed reporting, respect all fields.

- opengever/maintenance/scripts/fix_non_persisted_values.py
Two more things we've discovered during script testruns:
- when a required field has been added to the schema we also need to persist those values on the objects
- the `document_date` of a mail can't be retrieved from versions but should be extracted from the mail header the same way as done by https://github.com/4teamwork/opengever.core/blob/a58cbbb0e3a89013efb8029d1e675eabc183716e/opengever/mail/mail.py#L434-L438
- documents with no lazy initial version seem to return an emtpy list as history metadata, handle such cases by falling back to `created`
> Handle required fields with defaults, add special handling for document_date of mails

- opengever/maintenance/configure.zcml
- opengever/maintenance/nightly_archival_file_job.py
- opengever/maintenance/scripts/archival_file_checker.py
This PR adds a script that produces
- a **report of documents missing their archival file**
- optionally **queues them for conversion**
and 
- a nightly job provider that **triggers conversion for those queued documents**.
> **Usage**: archival_file_checker.py [-n] [report_missing | queue_missing]
>
> The script takes one of two commmands:
>
> `report_missing`
>     Reports all documents missing their archival file.
>
> `queue_missing`
>     Reports the documents, and additionally queues them for conversion by
>     a nightly job (by adding them to a persistent queue on the site root).
>
> The script will display some basic console output, and automatically log
> that ouput and some more detailed information to a logfile.
Identifying the documents that should have an archival file, but …
> Add nightly job and script to queue missing archival file conversions.

- opengever/maintenance/nightly_archival_file_job.py
Based on experiences from production, Bumblebee can convert up to 1 doc/s. We therefore increase the nightly limit for now.
> Nightly archival file job: Bump max conversion request to 2000.

- opengever/maintenance/scripts/update_inbox_group.py
https://extranet.4teamwork.ch/support/stadt-nidau/tracker-gever/140
We were discussing whether we should implement the whole thing as an upgrade step. I decided against it and implemented a parameterizable script instead. Which should be good for now, moving this to opengever.core could be part of the `Personalmutation OGIP`. I made me a note.
See https://github.com/4teamwork/opengever.nidau/issues/35
> Add InboxGroupMigrator script to solve support issue after inbox_group change.

- opengever/maintenance/nightly_archival_file_job.py
The first runs has shown that we can handle 10'000 docs in the given time window.
> Raise CONVERSION_REQUESTS_PER_NIGHT limit for conversion job.

- opengever/maintenance/scripts/fix_non_persisted_values.py
I've checked all the added fields, they're not required and does not have any default value.
Used for https://github.com/4teamwork/opengever.zug/issues/324
> Handle customer specific behavior fields in the persist_default values scripts.

- opengever/maintenance/scripts/archival_file_checker.py
These are two small fixes to the logic for which documents exactly should have an archival file (or rather, should be _reported_ as needing one, and queued if they don't):
- Ignore dossiers in the private area
- Ignore documents whose archival file conversion state is `STATE_FAILED_TEMPORARILY`
The `STATE_FAILED_TEMPORARILY` state is more of a permanent failure in most cases. It rather means that Bumblebee did in fact post back an explicit error response. This could happen for unsupported file formats, or in cases where Bumblebee is able to detect a PDFTools timeout because of a problematic file.
Both these cases are unlikely to be resolved by retries, so we skip documents in state `STATE_FAILED_TEMPORARILY` for now (eventually we might want a separate script (or flag) to find these).
> ArchivalFileChecker: Tweak logic for which docs should have archival files a bit

- opengever/maintenance/tests/test_grokking.py
- setup.py
Fixes test failures.
Because `opengever.maintenance` indirectly relies on some of `ftw.bumblebee`'s testing layers, we also need to pull in `ftw.bumblebee[tests]` as a testing dependency.
> Testing: Drop unittest2

- opengever/maintenance/configure.zcml
Make the import of the `.monitor` subpackage inside `opengever.maintenance` conditional.
If `ftw.monitor` is installed, we don't want to start a monitor server from `opengever.maintenance` the "legacy way".
> Only include .monitor package if ftw.monitor is not installed.

- test-og-2019.4.x.cfg
New release 2019.4.0 has been shipped.
> Add test buildout for the 2019.4.x releases.

- opengever/maintenance/scripts/reopen_and_close_rr_dossiers.py
Used for https://extranet.4teamwork.ch/support/gever-st-gallen/tracker-ris/12
The script provides two modes:
**`reopen`** reopens all resolved dossiers with a start date later than the specified with the -d parameter and stores a list of the dossier uids in the annotations of the plone site.
**`closed`** try to resolve the dossier, stored in the annotations list (see above) 
The script only works for deployments with a `lenient` resolver, because the use of `getFolderContents` in the all supplied check, does not work in bin/instance run scripts. Will open up separate issue for that.
> Add maintenance script to reopen dossiers and close them at a later time.

- opengever/maintenance/scripts/update_object_ids.py
This script allows to update the ID (which appears as part of the URL) of one or more objects.
Given a file with a list of paths, it will check for each of these objects what its ID would be (if it were newly created with that title), and rename it if necessary.
Usage:
```
bin/instance run update_object_ids.py [-n] <file_with_paths>
```
- IDs of parents or children won't be checked/updated - only the ID of the object
directly addressed by the given path. So this script is **NOT recursive**.
- **Journaling will be disabled for any renames**. Therefore there won't be any journal entries for this operation.
- Necessary reindexing (for example of the `path`) will be propagated down the subtree however. So all objects below should be reindexed properly. This currently is not optimized at all …
> Add script to update object IDs (e.g. URLs after changing title)

- opengever/maintenance/scripts/activate_solr.py
We clear the lexicon, then reindex all remaining `ZCTextIndices`. For most deployments this is only `Title`. For some we have added the filing_no customization which adds its own `ZCTextIndex`, `searchable_filing_no`. This index also needs to be rebuilt after activating solr.
Related to https://github.com/4teamwork/opengever.core/pull/6214.
> Also reindex filing_no if index is available.

- opengever/maintenance/scripts/show_preserved_as_paper_default.py
Simple script that dumps the corresponding registry value.
Is already running like that in production, I'm just checking it in here in case we need to do it another time.
> Add script to show 'preserved_as_paper_default' value.

- docs/HISTORY.txt
- opengever/maintenance/scripts/bumblebee_installation.py
This option is meant to be used after a bundle import to calculate and
reindex bumblebee checksums. Unlike reindex it only processes documents
where the checksum is missing.
During reindex collective.indexing is disabled to avoid postponing
the work to the commit phase.
Requires https://github.com/4teamwork/ftw.bumblebee/pull/132
> Add option to index bumblebee checksums

- test-og-2020.2.x.cfg
- test-og-develop.cfg
Unfortunately i had to temporarily make sure that `unittest2` is included for tests against current master. It seems that it was removed from most packages as a dependency, that's why it is no longer required. Unfortunately `ftw.keywordwidget` needs it, but we do not include `ftw.keywordwidget[test]` dependencies. I propose to add this simple workaround until we upgrade `ftw.keywordwidget` to a newer version.
> Bump tests for 2020.2.x to 2020.2.6.

- test-og-2017.6.x.cfg
- test-og-2017.7.x.cfg
- test-og-2018.1.x.cfg
- test-og-2018.2.x.cfg
- test-og-2018.3.x.cfg
- test-og-2018.4.x.cfg
- test-og-2018.5.x.cfg
- test-og-2020.6.x.cfg
Add tests against `2020.6.x`.
Jira: https://4teamwork.atlassian.net/browse/GEVER-723
> Add tests against 2020.6.x

- bootstrap.py
- opengever/maintenance/scripts/reindex_is_subtask_in_solr.py
- opengever/maintenance/scripts/reindex_path_depth_in_solr.py
It seems that we've had issues during the update from solr 7 to solr 8 for Köniz. This led to fields that were introduced / updated in solr during that update to end up not being updated. It seems that two fields were concerned, `path_depth` and `is_subtask`. `path_depth` was already fixed in https://github.com/4teamwork/opengever.maintenance/pull/225, here we add a similar script to index `is_subtask` where necessary. 
The corresponding upgrade step was https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20190827180126_replace_is_subtask_field_index_with_a_boolean_index/upgrade.py
I also update `bootstrap.py` and fix the batching in the script introduced for `path_depth`
For https://4teamwork.atlassian.net/browse/CA-1112
> Add script to reindex is_subtask in solr.

- opengever/maintenance/scripts/mark_dossiers_linked_with_workspaces_and_dump_links.py
- opengever/maintenance/scripts/set_external_reference_for_workspaces.py
Newly, dossiers that are linked to a workspace should be marked with an `ILinkedToWorkspace` interface. In addition, the `external_reference` field of the workspace should contain the `Oguid` of the linked dossier.
Since GEVER and Teamraum are two separate installations, the modifications cannot be migrated automatically. Therefore two migration scripts were written for this purpose.
The first script marks all linked dossiers with the interface. This is done in this script, since all dossiers have to be checked anyway to see if they are linked. Therefore it does not make sense to do this separately in an upgrade step. Also the links dossier <-> workspace are saved in a json file.
The second script reads the generated JSON file and saves the `Oguid` of the linked dossier as …
> Migrate external reference for workspaces

- docs/HISTORY.txt
- opengever/maintenance/scripts/cleanup_todo_notifications.py
The added script deletes notifications for activities on `ToDo`s that were incorrectly sent. These were due to a bug adding new participant of a `Workspace` as `Watcher` on all `ToDo`s and not just the ones in that particular `Workspace`.
Note that it is not possible to know which `Notification`s were wrongfully sent, as we cannot know what users were legitimate `Watcher`s at the time of the `Activity`. Instead, we delete all notifications for `ToDo` activities that were sent to users who are not currently `Watcher` on the corresponding `Resource`.
For https://4teamwork.atlassian.net/browse/CA-1324
> Add script to cleanup notifications for ToDo activities.

- opengever/maintenance/scripts/rename_deployment.py
This adds a script that allows to (selectively) rename some user visible titles / names of a deployment.
Required to perform the `DI.GVA` -> `DI.AGG` rename for Zug. Probably best reviewed in tandem with https://github.com/4teamwork/opengever.zug/pull/410 
The script allows to set the following properties to new values:
- AdminUnit title
- OrgUnit title
- Deployment title (-> Plone site id, email "from" name)
- AdminUnit abbreviation
Depending on what properties are changed, the required reindexing tasks are performed:
- Changing the AdminUnit abbreviation will perform the necessary reindexing operations for the reference number in the Catalog, Solr and SQL
- Changing the AdminUnit title will, if the `--migrate-filing-numbers` flag is also given, migrate all filing numbers using string …
> Add script to rename deployment properties

- opengever/maintenance/scripts/repository_migration.py
This implements one additional check. Because only entries that are in the excel are actually considered during some of the validations, it is important that all existing repofolders have an entry in the migration Excel. This is much easier than having to check both for positions in the excel and already existing positions (together with moves, merges, etc.).
https://4teamwork.atlassian.net/browse/CA-1266
> HBA migration: make sure that all repofolders have an entry in the migration excel.

- opengever/maintenance/scripts/list_trashed_document_templates.py
According to https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/123077675/GEVER+Releases+Versions-Spezifische+Punkte we should double-check trashed document templates. We'll use the script suggested in https://github.com/4teamwork/opengever.core/pull/6793#issuecomment-757842941 but check it in so we can run it easily for all deployments.
Jira: https://4teamwork.atlassian.net/browse/CA-1298
> Add script to print trashed document templates.

- opengever/maintenance/scripts/initialize_title_en.py
We add a new script that initializes the `title_en` field for all concerned portal_types. The script can build up a glossary from a repository excel file and use it to translate the titles of repository roots and folders. For other portal_types it uses a default glossary. When it does not find a given title in the glossary it simply uses the German title instead.
For https://4teamwork.atlassian.net/browse/CA-1040
> Add script to initialize title_en.

- opengever/maintenance/scripts/list_trashed_document_templates.py
Add a `--delete` option which allows to automatically remove all trashed templates. As discussed in https://4teamwork.atlassian.net/browse/CA-1298?focusedCommentId=21220  that's the strategy we want to use, at least for SaaS.
Jira: https://4teamwork.atlassian.net/browse/CA-1298
> Add option to delete trashed document templates.

- opengever/maintenance/scripts/repository_migration.py
We add the possibility to split the task syncing to a different step, as the migration itself is done on an OGDS that is not the productive one. For that we pickle the migrator object which knows which tasks will then have to be synced. This last step will be done in debug mode.
For https://4teamwork.atlassian.net/browse/CA-1267
> Improve repository migration scripts

- opengever/maintenance/scripts/allow_pdfconverter_removal_upgrade.py
This adds a script which sets the flag (in Plone site annotations) that allows the upgrade from https://github.com/4teamwork/opengever.zug/pull/412 to run.
Jira: https://4teamwork.atlassian.net/browse/CA-1275
> Add script to allow pdfconverter upgrade for a given deployment.

- opengever/maintenance/scripts/repository_migration.py
- We allow setting new permissions on existing repository folders. Note that we only do this if inheritance is blocked and local_roles are indicated in the Excel. These will replace the existing sharing permissions
- We skip the docproperties update
- We add commits during the migration, this is a test to see whether it will make the migration faster.
- I also improved logging a bit.
Tests were also updated, see https://github.com/4teamwork/opengever.core/pull/6792
For https://4teamwork.atlassian.net/browse/CA-1472
> Improve OS migration script

- opengever/maintenance/scripts/repository_migration.py
SG is now on the `opengever.core` version 2021.5.1, so we also need to reindex the newly introduced `sortable_reference` index in solr during the OS migration.
For https://4teamwork.atlassian.net/browse/CA-1959
> Also reindex sortable_reference during OS migration.

- test-og-2019.1.x.cfg
- test-og-2019.2.x.cfg
- test-og-2019.3.x.cfg
- test-og-2019.4.x.cfg
- test-og-2020.1.x.cfg
- test-og-2020.12.x.cfg
- test-og-2020.2.x.cfg
- test-og-2020.3.x.cfg
- test-og-2020.4.x.cfg
- test-og-2020.5.x.cfg
- test-og-2020.6.x.cfg
- test-og-2020.7.x.cfg
- test-og-2020.8.x.cfg
- test-og-2021.1.x.cfg
- test-og-2021.2.x.cfg
- test-og-2021.4.x.cfg
- test-og-2021.6.x.cfg
Drop testing against versions we no longer use in production according to matrix.
> Don't tests versions no longer used in production.

- test-og-2019.5.x.cfg
- test-og-2019.6.x.cfg
We cannot buildout reliably with the old pinned setuptools versions, so we pin the test builds to use a newer version.
I'm expecting most 2019.X versions to go away soon in any case.
This makes sure tests against `master` are green again.
> Also use setuptools 44.1.1 for older versions.

- opengever/maintenance/scripts/set_preserved_as_paper_to_false.py
Add a small script to set `preserved_as_paper` to False for all `IDocumentMetadata`. We probably could have run it in a debug shell but then again having progress logging and a dry-run mode is useful IMO.
Jira [CA-2772](https://4teamwork.atlassian.net/browse/CA-2772)
> Add script to set `preserved_as_paper` to False.

- docs/HISTORY.txt
- opengever/maintenance/browser/health_check.py
This uses the `nightly_run_within_24h()` and `ogds_sync_within_24h()` functions introduced in 4teamwork/opengever.core#7176 to provide an extended mode for the `@@health-check` view:
```
GET http://localhost:8080/fd/@@health-check?extended=1
{
"status":"healthy",
"instance":{
"instance_status":"healthy"
},
"nightly_jobs":{
"nightly_jobs_status":"healthy",
"last_nightly_run":"2021-09-20T17:48:54.225458",
"job_counts":{
"maintenance-jobs":5,
"deliver-sip-packages":0,
"trigger-missing-archival-file-conversion":0,
"complete-role-assignment-reports":0,
"execute-after-resolve-jobs":0
}
},
"ogds":{
"ogds_sync_status":"healthy",
"last_ogds_sync":"2021-09-20T17:46:38.552990"
}
}
```
_(Whitespaced added for clarity - actual response contains all the JSON on one line)_
If any of these two are not …
> Add extended health checks (Nightly Jobs and OGDS sync).

- opengever/maintenance/browser/health_check.py
Drop nightly  `job_counts` from `@@health-check view`. They turned out to not be side-effect free yet, and prevent access to the
`@@health-check` view for Anonymous users.
> Drop nightly job_counts from @@health-check view

- opengever/maintenance/scripts/print_ldap_sync_config.py
To be able to configure the AppSwitcher correctly in Teamraum deployments and display all available AdminUnits/OrgUnits, we need to sync all the corresponding groups to the Teamraum LDAP. Writing the configuration file for the LDAP sync can be a pain for deployment with man such OrgUnits. This script will simply print out that part of the ldapsync config file, i.e. source and target groups for all OrgUnits.
For https://4teamwork.atlassian.net/browse/CA-2821
> Add script to help creating an ldapsync config file.

- opengever/maintenance/scripts/add_intergever_webaction.py
This script adds a webaction on dossiers for eCH-0147 export via InterGEVER.
If a webaction with the same title already exists, the script skips the registration to avoid duplicate actions.
For [CA-2789](https://4teamwork.atlassian.net/browse/CA-2789)
> Add script to add InterGEVER webaction.

- test-og-2021.23.x.cfg
From 2021.23.0. Not from 2021.23.2. :(.
For [CA-2746](https://4teamwork.atlassian.net/browse/CA-2746)
> Bump tests to 2021.23.3.

- opengever/maintenance/scripts/set_registry_value.py
Add script to set an arbitrary registry record to a given value.
Expects the command line argument `<value>` to be given as a string representing a Python literal, which is then parsed using `literal_eval`. 
Example:
```
bin/instance run set_registry_value.py opengever.base.interfaces.IGeverUI.is_feature_enabled True
```
For [CA-3456](https://4teamwork.atlassian.net/browse/CA-3456)
> Add script to set an arbitrary registry record to a given value.

- docs/HISTORY.txt
- opengever/maintenance/scripts/repository_migration.py
- opengever/maintenance/scripts/update_object_ids.py
To finally get a few benefits, I had to modify the migration script quite a bit. Before we were generating a mapping of old and new positions in the order of the rows in the excel file and at the same time analysing the corresponding operation. This made the whole script very sensitive to operation ordering in the excel file, and defining the correct order was really not always easy (as the operations themselves actually happen in the order `create`, `move`, `merge`). Moreover we were sometimes using `position`s (i.e. reference numbers) to identify the parents (for example for creation operations). All the creation operations happening first,  can lead to temporarily having 2 repository folders with the same reference number (e.g. are creating a new repofolder having the same number as an …
> Improve repository migration script

- opengever/maintenance/scripts/check_workspace_participants.py
This script allows to verify that local roles on the migrated objects satisfy the restrictions we have in Teamraum, i.e. only users with permissions on a parent object can have local roles on a child object, and only objects with blocked inheritance can have local roles.
This is for https://4teamwork.atlassian.net/browse/CA-1481
> Add script to check workspace folder participation validity.

- docs/HISTORY.txt
- opengever/maintenance/scripts/repository_migration.py
We add support for the metadata fields (`IClassification` and `ILifeCycle` behaviours) for repository folders created during repository migration.
For [CA-3245]
[CA-3245]: https://4teamwork.atlassian.net/browse/CA-3245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set Metadata when creating new positions in repository migration. 

- opengever/maintenance/scripts/check_workspace_participants.py
Sorting makes the output a bit easier to read. I've now also added a new column with the titles of the objects, that also helps the customer assess what to do with these objects.
For https://4teamwork.atlassian.net/browse/CA-3712
> Sort misconfigured objects by path in ParticipantsChecker.

- opengever/maintenance/scripts/check_workspace_participants.py
- opengever/maintenance/utils.py
We modify the script used to check whether local roles respect the restrictions imposed in the new teamraum to allow correcting them. What the script will do:
- Correct participations with multiple roles: each participant should only have a single role (we keep the one giving the most permissions)
- Remove participants with same roles (or lower permissions) as on parent and inheritance that is not blocked.
- Delete participants that are not participants on the parent object
- Block inheritance on objects with local roles and copy roles from parent.
For https://4teamwork.atlassian.net/browse/CA-3712 and https://4teamwork.atlassian.net/browse/CA-3713
> Implement fixing of participations for migrated teamraum deployments.

- test-og-2022.4.x.cfg
Bump tests: opengever.core `2022.4.1`.
> Bump tests: opengever.core 2022.4.1

- opengever/maintenance/scripts/assign_global_role.py
Maintenance script that allows to globally assign a role to a principal (via `portal_role_manager`).
For [CA-2880](https://4teamwork.atlassian.net/browse/CA-2880)
> Add script to globally assign role to principal.

- opengever/maintenance/scripts/set_nightly_jobs_time_window.py
Add script to set nightly jobs time window.
(This is required because the existing `set_registry_value.py` script parses / casts any Python literals - but something like `datetime.timedelta(hours=23)` can't be expressed as a Python literal).
For [CA-2880](https://4teamwork.atlassian.net/browse/CA-2880)
> Add script to set nightly jobs time window.

- opengever/maintenance/scripts/connect_to_intergever.py
This extends the script to connect a GEVER deployment to InterGEVER with
- creation of the `intergever.app` service user (if it doesn't already exist)
- assigning the required roles (if not already assigned yet)
I already tested this script like this on `dev.onegovgever.ch`
For [CA-3274](https://4teamwork.atlassian.net/browse/CA-3274)
> Extend script to create InterGEVER service user and assign roles

- opengever/maintenance/scripts/make_repository_readonly.py
This adds a script that makes an entire repository read only by removing roles other than `Reader` from local role assignments.
The script's implementation deviates slightly (for repo roots) from what I specified in the story:
> Auf dem Ordnungssystem-Root sollen die Berechtigungseinstellungen fix wie folgt gesetzt werden:
>
> - Benutzer-Gruppe des Mandanten: Lesen
> - [x] Berechtigungen von übergeordneten Ordnern übernehmen
> 
> Möglicherweise vorhandene andere lokale Rollen sollen entfernt werden.
Instead, it does exactly the same thing for all nodes, repository root or otherwise: Remove all roles except `Reader` from any local role assignments. This gurantees that the `View` permission doesn't change, and we never have to reindex security, making the script much faster. In practice, …
> Add script to make an entire repository read-only.

- opengever/maintenance/scripts/make_repository_readonly.py
There are some objects where the `Owner` role is set through our role assignments (https://github.com/4teamwork/opengever.core/blob/master/opengever/base/role_assignments.py#L380), so it also needs to be allowed to replace that role with `Reader`, especially since that role does give various permissions.
For https://4teamwork.atlassian.net/browse/CA-3968
> Allow removing Owner role when making repository read-only.

- test-og-2022.4.x.cfg
> Bump GEVER version 2022.4 to latest hotfix release.

- opengever/maintenance/scripts/sql_contact_migration.py
The bin/instance run script will be used to migrate from the SQL Contact implementation to KuB. The Script does three jobs:
* **Creating a kub-bundle** for all persons, organizations and org_roles currently existing as sql contacts. The bundle only contains a minimal set of metadata. The complete set of metadata, addresses etc. will be imported to KuB by https://github.com/4teamwork/kub-migration-stabs.
* **Migrate all dossier participations**, they currently stored as SQLParticipations.
* **Reset contacts in manual journal entries**
* **Delete all sql contacts data** (should only be run after a successfully migration)
The participation migration and journal cleanup can be skipped.
For [CA-2536](https://4teamwork.atlassian.net/browse/CA-2635)
> Add Script for SQL contacts migration

- opengever/maintenance/scripts/sql_contact_migration.py
In earlier GEVER versions it was apparently possible to store multiple
participations for one contact or org_role. On the production system we have such duplicate participations.
Additional fix for #327 ([CA-2536](https://4teamwork.atlassian.net/browse/CA-2635))
> Handle duplicate participation entries.

- opengever/maintenance/scripts/add_propertysheets.py
- opengever/maintenance/scripts/example_propertysheets.json
it expects a json file with the corresponding informations. An example json file is added.
so we can only add the propertysheets.json to the policies and don't need to copy & paste the same script in all policies.
> Add simple script to add propertysheets from the console.

- test-og-2022.16.x.cfg
Add tests for opengever.core version 2022.16.0
For [CA-4085](https://4teamwork.atlassian.net/browse/CA-4085)
> Add tests for opengever.core version 2022.16.0

- opengever/maintenance/scripts/export_and_close_dossiers.py
- Handle slashes in the dossier title
- Temporary disable the workspaceclient registry flag. Because zopemaster is not able to communicate with the teamraum, the dossier resolving would fail, if the workspaceclient feature is enabled.
> Some small fixes in the dossier export script after first productive run.

- opengever/maintenance/scripts/contact_removal.py
For some clients we want to enable and integrate our KuB solution. Therefore we need to remove the contact data, which was never be used in a really productive manner. 
For CA-4939
> Add script to remove all plone contacts and dossier participations.

- docs/HISTORY.txt
Follow up of https://github.com/4teamwork/opengever.maintenance/pull/349, where I forgot to include my changelog entry.
For https://4teamwork.atlassian.net/browse/CA-5119
> Add forgotten changelog entry.

- opengever/maintenance/scripts/plone_contact_migration.py
This script is used to migrate the plone contacts to KuB. It is based on the [SQL contact migration script](https://github.com/4teamwork/opengever.maintenance/blob/master/opengever/maintenance/scripts/sql_contact_migration.py). It includes the following steps:
- Create a bundle to be imported into KuB.
- Migrate the dossier participations to KuB participations
- Delete the Plone contacts
- Delete the Contactfolder
Note that the some of the data from the Plone contacts has to be transformed to be imported into KuB, e.g. the country has to be mapped to an ISO Country code, house numbers have to be extracted from the `street` field.
Because certain fields are mandatory on the KuB side (Country and town for an address), we set missing countries to `CH` and skip addresses with missing Town. …
> Add script to migrate plone contacts to KuB

- opengever/maintenance/scripts/plone_contact_migration.py
When creating entities over the UI, these get set automatically, but not when importing a bundle. This then leads to our actor cards no showing any data for the migrated contacts...
For https://4teamwork.atlassian.net/browse/CA-2605
> Set is_default for address, phone, mail and url in plone contact migration.

- opengever/maintenance/scripts/export_and_close_dossiers.py
Add an option to include the repository folder structure and the subdossiers when exporting the dossiers and documents.
For https://4teamwork.atlassian.net/browse/CA-5061
[CA-5061]: https://4teamwork.atlassian.net/browse/CA-5061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dossier export can include repository and subdossier structure.

- opengever/maintenance/scripts/extract_gdgs_documents.py
- opengever/maintenance/scripts/find_orphaned_tasks.py
- opengever/maintenance/scripts/import_extracted_gdgs_documents.py
These scripts were used to recover data (Documents, Dossiers, ...) that was created/modified between the most recent Data.fs backup from Abraxas (2023-01-23 04:00) and the point when we set the deployment to read-only mode (2023-01-25 15:20).
Object metadata and blobs were extracted with the extraction script from the corrupted Database, and re-imported on top of the restored Abraxas Backup using the import script.
The script to find orphaned tasks was needed because when those tasks for GDGS were recreated on a staging deployment, the got written to an OGDS that wasn't reconciled back into the PROD OGDS (we just copied over Data.fs and Solr from the staging deployment back to PROD).
For 
https://4teamwork.atlassian.net/browse/CA-5305
https://4teamwork.atlassian.net/browse/CA-5290 …
> Add scripts used in the data recovery for GDGS

- opengever/maintenance/scripts/fix_refnum_mappings.py
When a repofolder gets moved (how that happens is still unclear), then we are left with a valid intid in the mapping, which will lead to the reference prefix [still being considered as used](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/adapters.py#L192-L198). Here we update the script cleaning up the mappings to cover that case.
As we currently also have a bug that reference numbers of repofolders do not get indexed properly when the prefix of the parent is changed (https://4teamwork.atlassian.net/browse/CA-4553), and as issues leading to the problems fixed by this script might also have led to incorrect indexing, I also add an option to reindex all repository folders. This makes a rather big transaction which might be slow to commit.
For …
> Improve script to fix reference number mappings on repository folders.

- opengever/maintenance/scripts/export_subtree_bundle.py
- opengever/maintenance/scripts/map_areg_bdgs_migration_bundle.py
Add script to export a subtree as an OGGBundle.
Also includes a script to then transform such a bundle in a way where dossiers get mapped to an already existing repository folder on the target deployment where the bundle will be imported.
Note: The import of a bundle generated this way showed that for `ftw.mail.mail` objects, the filename was not updated based on the title, but left as the filename from the bundle (`file_1.msg`, ...). Therefore those objects need to be fixed in the debug shell afterwards by calling `mail.update_filename()`.
For [CA-5415](https://4teamwork.atlassian.net/browse/CA-5415)
---
These are the steps that were performed for the test export and -import:
1) Export bundle
```bash
bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/export_subtree_b …
```
> Add scripts to export a subtree as an OGGBundle and transform it for CA-5415

- test-og-2019.5.x.cfg
- test-og-2019.6.x.cfg
- test-og-2020.10.x.cfg
- test-og-2020.11.x.cfg
- test-og-2020.13.x.cfg
- test-og-2020.14.x.cfg
- test-og-2020.15.x.cfg
- test-og-2020.9.x.cfg
- test-og-2021.10.x.cfg
- test-og-2021.11.x.cfg
- test-og-2021.12.x.cfg
- test-og-2021.13.x.cfg
- test-og-2021.14.x.cfg
- test-og-2021.15.x.cfg
- test-og-2021.16.x.cfg
- test-og-2021.17.x.cfg
- test-og-2021.18.x.cfg
- test-og-2021.19.x.cfg
- test-og-2021.3.x.cfg
- test-og-2021.5.x.cfg
- test-og-2021.7.x.cfg
- test-og-2021.8.x.cfg
- test-og-2021.9.x.cfg
We do not have any real deployment on a version older than 2021.21.
For https://4teamwork.atlassian.net/browse/CA-5655
> Remove test files for versions < 2021.19.

- opengever/maintenance/scripts/add_propertysheets.py
- opengever/maintenance/utils.py
With this PR we alle the use of references in the json file defining the propertysheets that are imported using the `opengever/maintenance/scripts/add_propertysheets.py` script. We also make a few other improvements in the script.
For https://4teamwork.atlassian.net/browse/CA-5768
> Improve script to import propertysheets

- opengever/maintenance/scripts/migrate_groups.py
With this PR we massively speed up the group migration by avoiding the use of `reindexObjectSecurity`. Instead we directly modify the security indexes in plone and in solr, as a group migration is basically a search and replace in those indexes.
For the HBA migration update of the index took around 40 seconds, whereas we never found out how long `reindexObjectSecurity` would take as it never finished, but from discussions with @lukasgraf it seems that even when reindexing just one branch of the repository (the largest branch), reindexing the object security did not finish in a whole weekend.
For https://4teamwork.atlassian.net/browse/CA-5829
> Speedup group migration

- opengever/maintenance/scripts/fix_allowed_roles_and_users_after_group_migration.py
- opengever/maintenance/scripts/migrate_groups.py
The group migration script contained a bug: when migrating an `old_group` to a `new_group`, if there was already an entry in the forward index for the new_group, we overwrote that entry instead of updating it. This led to the forward entry not containing all the `rids` for such groups.
For https://4teamwork.atlassian.net/browse/CA-6361
> Fix group migration script and add script to rectify the allowedRolesAndUsers index on already migrated deployments

- opengever/maintenance/scripts/active_user_stats.py
This PR adds a new script to get the active user stats of a deployment.
Run it with
```
bin/instance0 run src/opengever.maintenance/opengever/maintenance/scripts/active_user_stats.py -v
```
to get the following output for a gever installation:
```
{
"timestamp": "2023-12-27T12:06:59.985791+01:00",
"total_active_unique_teamraum_users": 0,
"total_active_unique_gever_users": 267,
"total_active_unique_spv_users": 291
}
```
or for a teamraum installation:
```
{
"timestamp": "2023-12-27T12:06:59.985791+01:00",
"total_active_unique_teamraum_users": 170,
"total_active_unique_gever_users": 0,
"total_active_unique_spv_users": 0
}
```
The script uses the OGDS for the calculations. It should be run only once per OGDS.
> Add active_user_stats script

- test-og-2024.5.x.cfg
Test against 2024.5.1 release.
For [CA-6806](https://4teamwork.atlassian.net/browse/CA-6806)
[CA-6806]: https://4teamwork.atlassian.net/browse/CA-6806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Test against 2024.5.1 release.

- opengever/maintenance/scripts/connect_to_intergever.py
Add 'sgprod' cluster to connect_to_intergever.py
For [HG-4496](https://4teamwork.atlassian.net/browse/HG-4496)
[HG-4496]: https://4teamwork.atlassian.net/browse/HG-4496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix intergever URL for sgprod

- opengever/maintenance/scripts/fix_broken_intid_references.py
For: https://4teamwork.atlassian.net/browse/TI-23
This PR adds a new script to fix broken intid references.
In a first step, script will gather all broken objects and write the paths into a json file. In a second step, the script will fix those paths. So it's also possible to directly fix some specific objects without previously run a full check.
```shell
bin/instance run ./scripts/fix_broken_intid_references.py --check --fix
INFO Use the following output directory: var/maintenance-fix-broken-intid-references-22042024-143427
INFO Create output directory
INFO: Using Plone Site 'fd'.
INFO STARTING Check for broken intid references
INFO Found broken object: /fd/private
INFO 1 of 237 (0%): Check for broken intid references
INFO Found broken object: /fd/eingangskorb
...
INFO DONE Check for …
```
> Add maintenance script: fix_broken_intid_references

- opengever/maintenance/scripts/export_propertysheets.py
- opengever/maintenance/scripts/import_propertysheets.py
Export uses the REST API serializer.
Import uses a copy of the `create_property_sheet()` method from the REST API.
There's an `add_propertysheets.py` script that probably does the same, but I didn't figure out how to create dumps for this script.
> Add scripts for import and export of property sheets

- opengever/maintenance/scripts/repository_migration.py
We improve the performance and allow to have no blobs when indexing by patching the Catalog and only updating relevant metadata instead the full list of metadata.
The Catalog will always update all available metadata if reindexing an object with `update_metadata` enabled. There is no way to update only specific metadata values of an object. Updating metadata means, that all metadata will be recalcuated for an objects. This process takes a lot of time and is mostly unnecessary. In addition, it requires to have access to the blobs of documents because some of the metadata properties are relying on blob information (filesize). To speed up the migration and to be able to run the migration without the existence of blobs, we'll patch the catalog to only update the relevant metadata items.
> Improve metadata update handling in repository_migration script.

- opengever/maintenance/scripts/export_gever.py
Exports gever contents to a file system.
Following content types will become folders:
- `opengever.repository.repositoryroot`
- `opengever.repository.repositoryfolder`
- `opengever.dossier.businesscasedossier`
- `opengever.meeting.meetingdossier`
- `opengever.meeting.proposal`
Following content types will become documents:
- `opengever.document.document`
- `ftw.mail.mail`
> Add script to export a gever to a folder structure
