- docs/HISTORY.txt
- opengever/maintenance/browser/transmogrify.py
This allows us to do a "poor man's dry-run".
@deiferni
> Add option to doom transaction to @@transmogrify view.

- README.rst
> Added readme entry for the profile_version commands

- docs/HISTORY.txt
- opengever/maintenance/scripts/check_for_missing_refnum.py
This script should find all dossiers that are missing a reference number.
@phabegger
> Add script to find all Dossiers missing a reference_number.

- docs/HISTORY.txt
- opengever/maintenance/browser/warmup.py
A first draft of a view to warm up instance caches.
> Add very basic view to warm up instance caches.

- opengever/maintenance/scripts/fix_mail_class_intids.py
> Mail-fix: be a bit more intelligent with reindexing objects.

- docs/HISTORY.txt
- opengever/maintenance/scripts/fix_mails_with_no_subject.py
Script that identifies and/or fixes mails that have been indexed with `no_subject`.
> Add script to find and fix mails with no_subject.

- opengever/maintenance/scripts/rename_repository_folders.py
when they no longer correlate with the title.
Used for the AI [maintenance job](https://extranet.4teamwork.ch/support/gever-ai/tracker/113).
@lukasgraf @deiferni
> Added maintenance script to rename ids of repositoryfolders,

- docs/HISTORY.txt
- opengever/maintenance/browser/refnum_selfcheck.py
> Add view with reference number self-checks.

- docs/HISTORY.txt
- opengever/maintenance/browser/re_generate_excerpts.py
Re-generates already generated excerpts for a closed meeting.
> Add a browser-view to re-generate excerpts for a meeting.

- opengever/maintenance/browser/lock_maintenance.py
> Fix lock maintenance view.

- base-testing.cfg
- test-og-3.0.x.cfg
- test-og-3.2.x.cfg
- test-og-3.3.x.cfg
- test-og-3.4.x.cfg
- test-og-3.5.x.cfg
- test-og-3.6.x.cfg
- test-og-develop.cfg
Also cleanup and remove duplicated info by moving package-stuff to the base config.
> Add tests for OneGov GEVER 3.6.x

- opengever/maintenance/scripts/use_canonical_document_ids.py
This PR improves the script to rename document its by:
- Committing every 100 items
- Adding Progress-Log
- Removing too verbose logging, renamed items are written to a .csv file already, that is sufficient
> Commit in chunks when renaming 

- test-og-3.11.x.cfg
Test against latest 3.11 release.
> Use release 3.11.3 for the 3.11.x branch.

- test-og-3.11.x.cfg
The release contains a few bugfixes.
> Use release 3.11.4 for the 3.11.x branch.

- opengever/maintenance/scripts/bumblebee_installation.py
Add option to commit every N elements. This currently has only an effect when run with `-m history`.
> Add intermediate commit option to bumblebee activation.

- setup.py
> Actually normalize the dev version number

- MANIFEST.in
There are no .txt files in the project root.
> There are no .txt files in the project root to package into the egg

- test-og-2017.6.x.cfg
Test against 2017.6.4 bugfix release.
> Test against most recent 2017.6.x release.

- opengever/maintenance/scripts/fix_non_persisted_document_dates.py
Add script to fix non-persisted document dates (`IDocumentSchema['document_date']`).
xref: https://basecamp.com/2768704/projects/14549453/todos/337423674
> Add script to fix non-persisted document dates.

- docs/HISTORY.txt
- opengever/maintenance/scripts/list_url_files.py
Add script to list `.url` files as a CSV report.
xref: https://basecamp.com/2768704/projects/12554551/todos/323733158
> Add script to list .url files.

- test-og-2018.1.x.cfg
> Add tests for new GEVER release 2018.1.4.

- test-og-2018.2.x.cfg
> Bump tests to 2018.2.4 release.

- opengever/maintenance/scripts/reset_custody_period.py
- opengever/maintenance/scripts/reset_retention_period.py
See https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/25
> Add script to reset retention period

- opengever/maintenance/scripts/find_non_persisted_document_metadata.py
Add script to find documents with non-persisted metadata.
> Add script to find documents with non-persisted metadata.

- opengever/maintenance/scripts/find_objects_with_missing_intids.py
Closes https://github.com/4teamwork/opengever.core/issues/4754
> Add a script to log objects with missing IntIds

- opengever/maintenance/scripts/find_objects_with_missing_intids.py
* Forgot to import argparse
* Actually broken objects behave differently than the ones I broke in testing
> Fix the missing intid script

- test-og-2017.2.x.cfg
- test-og-2018.1.x.cfg
- test-og-2018.2.x.cfg
- test-og-2018.3.x.cfg
- test-og-2018.4.x.cfg
> Bump to 2018.3.7. Also bump other old releases.

- opengever/maintenance/browser/warmup.py
Load catalog BTrees and forward index BTrees of the most used indexes.
The warmup view needs to be called for the number of threads in parallel, e.g:
```
for i in {1..2}; do (curl -s http://localhost:10101/fd/mnt-warmup?mode=catalog >/dev/null && echo "$i done." &) ; done
```
> Add catalog warmup

- test-og-2018.5.x.cfg
> Add 2018.5 test cfg.

- test-og-2018.5.x.cfg
2018.5.7 hotfix release has been released ...
> Bump version for 2018.5 tests to latest hotfix.

- opengever/maintenance/scripts/add_missing_file_extensions.py
We need to correct the filename extensions of documents on the whole plone site. As all the problematic documents were generated by the same user, we add a new `creator` filter for the query, to limit the number of objects we need to get.
This is for:
https://extranet.4teamwork.ch/support/ph-vs/tracker/534/
> Add new creator parameter to add_missing_file_extension script.

- test-og-2019.2.x.cfg
> Bump 2019.2 test cfg to latest release 2019.2.4.

- opengever/maintenance/scripts/fix_non_persisted_values.py
We have attempted to run the fix for a customer and discovered some more fields that should be handled. 
I have also improved logging output a bit by also displaying schema name in some error messages, this allows to easier locate the affected field.
Also fixed some bugs in dusty code paths 😉.
_The commits are very fine grained, one per field, and can be squashed on demand._
> Add support for more fields as encountered on customer site.

- opengever/maintenance/scripts/archival_file_checker.py
Querying the catalog for `after_resolve_jobs_pending=False` does not include objects with `Missing.Value`, only ones that actually are indexed with `False`.
We therefore need to check on the actual objects for pending after resolve jobs instead of relying on the catalog.
> ArchivalFileChecker: Correctly handle pending resolve jobs.

- opengever/maintenance/scripts/fix_non_persisted_values.py
According to the discussion we had in https://github.com/4teamwork/opengever.zug/issues/315#issuecomment-518150992.
> Add fallback for konsulmigration relicts to the persist defaultvalues script.

- test-og-2019.2.x.cfg
- test-og-2019.3.x.cfg
Part of https://github.com/4teamwork/opengever.core/wiki/Neuer-GEVER-Release.
> Make sure we test against all and latest releases.

- opengever/maintenance/scripts/archival_file_checker.py
This PR optimizes memory usage of the `archival_file_checker.py` script.
It does so by **passing around IntIds** (instead of keeping full objects around in memory), and employing the same "magic incantations" that we've already used to reduce the memory footprint for bundle imports:
Regularly
- trigger garbage collection of the cPickleCache
- trigger Python GC
- Unset and re-set the thread-local reference to the sitemanager
and
- run the script with a cache size of 0 (zero).
The downside of this is a slightly **slower runtime** (1m40s instead of 1m06s for my test scenario) and **less readable log output** (IntIds instead of Dossier/Document paths).
This significantly reduces memory growth as well as the memory high water mark. Below is a comparision with 10'000 documents (in 1000 …
> Optimize ArchivalFileChecker memory usage

- opengever/maintenance/scripts/fix_non_persisted_values.py
No defaults - not required fields.
> Add the spez. dossier fields of ISKARRCaseBehavior to the persist values script.

- opengever/maintenance/scripts/delete_spv.py
A script to delete all SPV contents. I hope I did not forget anything. I tested it locally.
> Add script to delete SPV contents.

- opengever/maintenance/scripts/list_dossiers_shared_with_group.py
Fix output and add a force option to allow listing the dossiers for a group that does not exist anymore.
> Update script to list dossiers shared with group

- opengever/maintenance/scripts/list_dossiers_shared_with_group.py
For https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/965
On kapo we run out of memory when executing this script. Using commit savepoints should help manage the memory usage.
I copied the memory management from https://github.com/4teamwork/opengever.maintenance/pull/192, and tested on `test.onegovgever.ch`, seems to work.
> Improve memory management in list_dossiers_shared_with_group.

- test-og-2020.2.x.cfg
> Bump tests for 2020.2.x to 2020.2.3.

- opengever/maintenance/scripts/set_emm_ip_ranges.py
For https://github.com/4teamwork/opengever.sg/issues/404
use with:
`bin/instance0 run src/opengever.maintenance/opengever/maintenance/scripts/set_emm_ip_ranges.py "10.73.79.22, 10.73.79.38, 10.73.71.6"`
> Add script to set EMM IP ranges.

- test-og-2020.2.x.cfg
> Bump tests for 2020.2.x to 2020.2.4.

- opengever/maintenance/scripts/update_object_ids.py
In https://4teamwork.atlassian.net/browse/GEVER-177 we have encountered errors while renaming as task syncing tried to resolve/traverse to objects where the int-id utility did not yet have a chance to update the path stored there, but the object itself had already been renamed.
This lead to a a `KeyError` as described in https://4teamwork.atlassian.net/browse/GEVER-177?focusedCommentId=14815.
With this PR we patch the event handler to make sure that syncing tasks is deferred until all objects have been moved.
> Defer syncing tasks while renaming objects.

- test-og-2020.3.x.cfg
- test-og-2020.4.x.cfg
- test-og-2020.5.x.cfg
> Bump tests for 2020.3.x to 2020.5.0.

- opengever/maintenance/scripts/update_object_ids.py
The handlers seems already imported at the time we attempt the simple monkey patch. Thus we switch strategy and actually patch the code to be executed.
There is no practical way to revert the patch, but:
- In case of multiple objects being renamed we will patch over our previous patch.
- To perform the deferred syncing the method body of `sync_task` is duplicated and copied into a helper method.
✅ I did a testrun for the changes (on a copy with just the metadata), renaming can be performed successfully.
But of course, suggestions are welcome if the reviewer can see a more elegant strategy to disable/defer task syncing.
For https://4teamwork.atlassian.net/browse/GEVER-177.
> Patch deferring task syncing with marmoset patch.

- test-og-2020.7.x.cfg
> Add tests against 2020.7.x

- test-og-2020.8.x.cfg
> Add tests against 2020.8.x.

- test-og-2020.8.x.cfg
😓 
Jira: https://4teamwork.atlassian.net/browse/GEVER-725
> Bump tests for 2020.8.x to 2020.8.1.

- test-og-2020.9.x.cfg
Jira: https://4teamwork.atlassian.net/browse/GEVER-726
> Add tests against 2020.9.x.

- test-og-2020.10.x.cfg
For https://4teamwork.atlassian.net/browse/CA-1068
> Add tests against 2020.10.x.

- test-og-2020.11.x.cfg
Jira: https://4teamwork.atlassian.net/browse/NE-113
> Add tests against 2020.11.x.

- opengever/maintenance/scripts/reindex_path_depth_in_solr.py
Add script to reindex `path_depth` in Solr.
Already executed on PROD, checking it in for traceability.
Jira: https://4teamwork.atlassian.net/browse/CA-957
> Add script to reindex path_depth in Solr.

- test-og-2020.12.x.cfg
Jira: https://4teamwork.atlassian.net/browse/NE-114
> Add tests against 2020.12.x.

- opengever/maintenance/scripts/check_solr_indices_removed.py
We don't seem to have removed them consistently for all deployments. I'd like to quickly check SaaS to get a damage assessment.
jira: https://4teamwork.atlassian.net/browse/CA-1141
> Add script to check if solr indices in catalog.

- test-og-2020.13.x.cfg
https://4teamwork.atlassian.net/browse/CA-1067
> Add tests against 2020.13.x.

- test-og-2020.14.x.cfg
Jira: https://4teamwork.atlassian.net/browse/NE-325
> Add tests against 2020.14.x.

- test-og-2020.14.x.cfg
See https://4teamwork.atlassian.net/browse/CA-1214
> Add tests against 2020.14.2

- test-og-2020.15.x.cfg
https://4teamwork.atlassian.net/browse/NE-369
> Add tests against 2020.15.0

- test-og-2020.14.x.cfg
> Add tests against 2020.14.5.

- test-og-2020.15.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1216
> Add tests against 2020.15.1.

- opengever/maintenance/scripts/fix_broken_linked_workspace_marker_interface.py
Add script to fix issues with broken `ILinkedWorkspacesMarker` interface (relation catalog and portal catalog's `object_provides`).
Checkin as-executed-in-production for traceability.
Jira: https://4teamwork.atlassian.net/browse/CA-1347
> Add script to fix issues with broken ILinkedWorkspacesMarker interface.

- test-og-2021.1.x.cfg
Jira: https://4teamwork.atlassian.net/browse/NE-370
> Add tests against 2021.1.0

- test-og-2021.2.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1298
> Add tests against 2021.2.0.

- test-og-2021.3.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1299
> Add tests against 2021.3.0.

- opengever/maintenance/scripts/initialize_title_fr.py
Very similar to the script initialising english titles. This one is a bit more careful, as French has been around for a while, it takes care not to overwrite French titles that would already have been set.
> Add script to initialize title_fr.

- test-og-2021.4.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1757
> Add tests against 2021.4.1.

- test-og-2021.5.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1758
> Add tests against 2021.5.0.

- test-og-2021.6.x.cfg
> Add tests against 2021.6.x.

- opengever/maintenance/scripts/fix_task_template_responsibles.py
Fixes: https://4teamwork.atlassian.net/browse/CA-1997
See for a detailed bug report: https://github.com/4teamwork/opengever.core/pull/6961
> Fix broken task template responsibles

- test-og-2021.8.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-1762
> Add test file for gever release 2021.8.0

- test-og-2021.9.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2028
> Add test file for gever release 2021.9.0

- test-og-2021.10.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2029
> Add test file for gever release 2021.10.0.

- opengever/maintenance/scripts/find_fields_with_non_persisted_default_values.py
This is based on the `find_non_persisted_values.py` script.
> Add script to check default values have been persisted on all objects.

- test-og-2021.15.x.cfg
- test-og-2021.16.x.cfg
https://4teamwork.atlassian.net/browse/CA-2495
> Add test file for gever release 2021.15.0 and 2021.16.0.

- test-og-2021.17.x.cfg
Add test file for GEVER release 2021.17.0
Jira: https://4teamwork.atlassian.net/browse/CA-2496
> Add test file for gever release 2021.17.0

- test-og-2021.18.x.cfg
https://4teamwork.atlassian.net/browse/CA-2510
> Add test file for gever release 2021.18.0.

- opengever/maintenance/scripts/initialize_title_fr.py
For https://4teamwork.atlassian.net/browse/CA-2864
> Fix initialize_title_fr script.

- test-og-2021.20.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2512
> Add test file for gever release 2021.20.

- opengever/maintenance/scripts/cleanup_dossier_permissions.py
Script only added for history and review reasons.
> Added script to cleanup the dossier permissions.

- test-og-2021.22.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-2514
> Add test file for gever release 2021.22.0.

- test-og-2021.23.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2515
> Add tests for release 2021.23.

- test-og-2021.24.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-2516
> Add tests against 2021.24.0

- test-og-2021.24.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-2516
> Add tests against 2021.24.1

- opengever/maintenance/scripts/propagate_restricted_field_value.py
Add maintenance script updates the values of the passed restricted field for all children of a given container, to make sure that the values for that field satisfy the restrictions.
https://4teamwork.atlassian.net/browse/CA-3239
> Add maintenance script to propagate restricted field values to children.

- test-og-2022.1.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-2518
> Bump tests to 2022.1.0

- test-og-2022.2.x.cfg
> Bump tests to 2022.2.0

- test-og-2022.3.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2873
> Add tests for opengever.core 2022.3.0.

- opengever/maintenance/scripts/count_contacts.py
For https://4teamwork.atlassian.net/browse/CA-2605
> Add script to count the plone contacts.

- opengever/maintenance/scripts/export_dossier_structure_as_excel.py
We update the script to export the dossier structure, adding links to the objects and allowing to export the whole repository.
For https://4teamwork.atlassian.net/browse/CA-3666
> Update script to export dossier structure.

- test-og-2022.4.x.cfg
Add tests for opengever.core 2022.4.0.
> Add tests for opengever.core 2022.4.0.

- test-og-2022.5.x.cfg
[CA-2875]
[CA-2875]: https://4teamwork.atlassian.net/browse/CA-2875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for opengever.core 2022.5.0.

- test-og-2022.4.x.cfg
For https://4teamwork.atlassian.net/browse/CA-3771
>  Bump tests: opengever.core 2022.4.3

- opengever/maintenance/scripts/set_cas_server_url.py
For https://4teamwork.atlassian.net/browse/CA-3828
> Add script to set the portal CAS URL.

- test-og-2022.4.x.cfg
Bump tests: opengever.core 2022.4.4
> Bump tests: opengever.core 2022.4.4

- test-og-2022.6.x.cfg
For https://4teamwork.atlassian.net/browse/CA-2876
> Add tests for opengever.core 2022.6.0.

- test-og-2022.8.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-4011
> Bump tests: opengever.core 2022.8.0

- test-og-2022.10.x.cfg
[CA-4079]
[CA-4079]: https://4teamwork.atlassian.net/browse/CA-4079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for opengever.core 2022.10.0

- test-og-2022.11.x.cfg
For https://4teamwork.atlassian.net/browse/CA-4080
> Add tests for opengever.core 2022.11.0.

- test-og-2022.12.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-4081
> Add tests for opengever.core 2022.12.0

- opengever/maintenance/scripts/sql_contact_migration.py
This allows us to migrate the participations without reindexing them and then import the kub contacts and reindex the participations later, when the contacts are already imported into KUB.
For CA-2635
> Move participation reindexing in to a separate step.

- test-og-2022.13.x.cfg
[CA-4082]
[CA-4082]: https://4teamwork.atlassian.net/browse/CA-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for opengever.core 2022.13.0

- test-og-2022.14.x.cfg
For https://4teamwork.atlassian.net/browse/CA-4083
> Add tests for opengever.core version 2022.14.0.

- opengever/maintenance/scripts/fix_non_persisted_values.py
- opengever/maintenance/scripts/fix_solr_filesize_and_changed.py
- opengever/maintenance/scripts/reindex_is_subtask_in_solr.py
- opengever/maintenance/scripts/reindex_path_depth_in_solr.py
For https://4teamwork.atlassian.net/browse/CA-4291
> Adapt scripts to new ftw.solr version 2.12.0.

- test-og-2022.15.x.cfg
For https://4teamwork.atlassian.net/browse/CA-4084
> Add tests for opengever.core version 2022.15.0.

- test-og-2022.17.x.cfg
Jira: https://4teamwork.atlassian.net/browse/CA-4086
> Add tests for opengever.core version 2022.17.0

- test-og-2022.18.x.cfg
[CA-4087]
[CA-4087]: https://4teamwork.atlassian.net/browse/CA-4087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for opengever.core version 2022.18.0

- opengever/maintenance/scripts/export_and_close_dossiers.py
For https://4teamwork.atlassian.net/browse/CA-4515
> Add script to export and close all dossiers inside a repofolder.

- test-og-2022.20.x.cfg
[CA-4089]
[CA-4089]: https://4teamwork.atlassian.net/browse/CA-4089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for opengever.core version 2022.20.0

- test-og-2022.21.x.cfg
For https://4teamwork.atlassian.net/browse/CA-4090
> Add test file for opengever.core version 2022.21

- opengever/maintenance/scripts/sql_contact_migration.py
[CA-2859 ](https://4teamwork.atlassian.net/browse/CA-2859)
> Adjust import in sql_contact_migration script.

- test-og-2022.23.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-4957
> Add tests for opengever.core version 2022.23.0

- opengever/maintenance/nightly_archival_file_job.py
For https://4teamwork.atlassian.net/browse/CA-5119
> Fix NightlyArchivalFileConversion for gever versions > 2021.18.0.

- opengever/maintenance/scripts/plone_contact_migration.py
Improve rendering of the tables by avoiding `None` and replacing it with empty strings.
For https://4teamwork.atlassian.net/browse/CA-2605
> Improve log output for plone contact migration.

- test-og-2023.2.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-5368
> Add tests for opengever.core version 2023.2.0

- test-og-2023.3.x.cfg
Add tests for 2023.3.
For [CA-5420](https://4teamwork.atlassian.net/browse/CA-5420)
[CA-5420]: https://4teamwork.atlassian.net/browse/CA-5420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for 2023.3

- test-og-2023.4.x.cfg
For https://4teamwork.atlassian.net/browse/CA-5496
> Add tests for 2023.4

- test-og-2023.5.x.cfg
For: https://4teamwork.atlassian.net/browse/CA-5534
> Add tests for 2023.5.1

- opengever/maintenance/scripts/custom_dossier_report.py
Add script to create customized XLSX dossier report.
This was developed to create the report for [CA-5426](https://4teamwork.atlassian.net/browse/CA-5426), but it should be pretty reusable.
[CA-5426]: https://4teamwork.atlassian.net/browse/CA-5426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add script to create customized XLSX dossier report.

- test-og-2023.8.x.cfg
For https://4teamwork.atlassian.net/browse/CA-5655
> Add new test file for release 2023.8.

- opengever/maintenance/scripts/bumblebee_store_dossier.py
Add script to store docs in a dossier in bumblebee.
For https://4teamwork.atlassian.net/browse/CA-6149
> Add script to store docs in a dossier in bumblebee.

- opengever/maintenance/scripts/migrate_groups.py
- opengever/maintenance/scripts/repository_migration.py
We make some improvements in the repository migration scripts and we move the group migration script to this package.
For https://4teamwork.atlassian.net/browse/CA-5829
> Improve migration scripts

- test-og-2024.1.x.cfg
Add tests for 2024.1.0.
For [CA-6576](https://4teamwork.atlassian.net/browse/CA-6576)
[CA-6576]: https://4teamwork.atlassian.net/browse/CA-6576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for 2024.1.0.

- test-og-2024.3.x.cfg
For [CA-6686](https://4teamwork.atlassian.net/browse/CA-6686)
[CA-6686]: https://4teamwork.atlassian.net/browse/CA-6686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for 2024.3.0.

- test-og-2024.5.x.cfg
Add tests for 2024.5.0.
For [CA-6806](https://4teamwork.atlassian.net/browse/CA-6806)
[CA-6806]: https://4teamwork.atlassian.net/browse/CA-6806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for 2024.5.0

- opengever/maintenance/scripts/connect_to_intergever.py
Add `sgprod` cluster to connect_to_intergever.py
For [HG-4496](https://4teamwork.atlassian.net/browse/HG-4496)
[HG-4496]: https://4teamwork.atlassian.net/browse/HG-4496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add 'sgprod' cluster to connect_to_intergever.py

- opengever/maintenance/scripts/connect_to_intergever.py
connect_to_intergever.py: Add support for updating existing webactions.
For [HG-4496](https://4teamwork.atlassian.net/browse/HG-4496)
[HG-4496]: https://4teamwork.atlassian.net/browse/HG-4496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> connect_to_intergever.py: Add support for updating existing webactions.

- opengever/maintenance/scripts/connect_to_intergever.py
Adding configurations for
- walenstadt
- pfaefers
- quarten
- sevelen
to register their interGEVER webactions
> Add clusters for walenstadt, pfaefers, quarten & sevelen

- test-og-2024.7.x.cfg
Add tests for 2024.7.0
For [TI-55](https://4teamwork.atlassian.net/browse/TI-55)
[TI-55]: https://4teamwork.atlassian.net/browse/TI-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tests for 2024.7.0

- opengever/maintenance/scripts/connect_to_intergever.py
[TI-429]
[TI-429]: https://4teamwork.atlassian.net/browse/TI-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding New "Mandanten"

- opengever/maintenance/scripts/connect_to_intergever.py
- Provide a web action in GEVER for "Import eCH-0147"
- Update the existing web action "Export via Inter-GEVER" to "Export eCH-0147/Inter-GEVER"
- Restrict import type to `repositoryfolder `
- Provide argument named `"jobs" `which will have a default value of `['webactions', 'service_user']`. This argument will allow us to specify manually which tasks should be executed.
> eCH-0147 import action

- opengever/maintenance/scripts/connect_to_intergever.py
Some fixes for the intergever webactions.
> Fix intergever webactions

- opengever/maintenance/scripts/connect_to_intergever.py
Update `connect_to_intergever.py` for new local development setup.
(Required for https://github.com/4teamwork/intergever/pull/141)
For [TI-503](https://4teamwork.atlassian.net/browse/TI-503)
[TI-503]: https://4teamwork.atlassian.net/browse/TI-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update connect_to_intergever.py for new local development setup.

- opengever/maintenance/scripts/migrate_groups.py
This substantially reduces the memory footprint of the `migrate_groups.py` script, and adds support for migrating groups used for Teams.
I executed this script like this on HBA yesterday for [TI-1466](https://4teamwork.atlassian.net/browse/TI-1466). The memory high watermark improved to about `700 MB` from previously `8 GB`.
For [TI-1466](https://4teamwork.atlassian.net/browse/TI-1466)
[TI-1466]: https://4teamwork.atlassian.net/browse/TI-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TI-1466]: https://4teamwork.atlassian.net/browse/TI-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Group migration script: Reduce memory footprint, add support for teams

- opengever/maintenance/scripts/propagate_archival_value_field.py
Add script to propagate archival_value field.
For [CA-6433](https://4teamwork.atlassian.net/browse/CA-6433)
[CA-6433]: https://4teamwork.atlassian.net/browse/CA-6433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add script to propagate archival_value field.

- opengever/maintenance/scripts/touch_modified_older_than_changed.py
Add script to touch items with changed date that is newer than modified.
(Executed like this for all deployments in SG).
For [CA-6552](https://4teamwork.atlassian.net/browse/CA-6552)
[CA-6552]: https://4teamwork.atlassian.net/browse/CA-6552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add script to touch items with changed date that is newer than modified.

- opengever/maintenance/scripts/fix_broken_intid_references.py
[TI-1834](https://4teamwork.atlassian.net/browse/TI-1834)
Allow fix broken intid script to be deployed for any path
[TI-1834]: https://4teamwork.atlassian.net/browse/TI-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow fix broken intid script to be deployed for any path

- opengever/maintenance/scripts/item_processor.py
Useful for maintenance scripts with a huge number of iterations.
> Implement conflict safe item processor with time estimation.
